### ISSUE TITLE
[Suggestion] Be able to set the logarithm base

### ISSUE THREAD

**Issue by tribly** [NerdyPepper/eva#30]
First of all, thanks for eva, really liking it!

Would it be possible to set the log base manually? Maybe like `log(2,3)` or something.

**Comment by oppiliappan** [comment]
the reason this is not possible at the moment, is because functions take only one argument. i think its about time i got around to reworking the parsing logic, this would allow functions like `max(a, b), sum(a, n)` and maybe even variadic functions.  
for now i suppose you could do `log2 / log3` haha!

im glad you like the program @tribly!

**Comment by pickfire** [comment]
This is fixed with https://github.com/nerdypepper/eva/commit/2f943ac30bc5c67b1b2c7305c6f7a8d1a5b9bbfc
