### ISSUE TITLE
Suggestion: How about prebuilt binaries for common os?

### ISSUE THREAD

**Issue by Frago9876543210** [NerdyPepper/eva#40]

**Comment by oppiliappan** [comment]
Ill get to work on this, for the time being, we could use Github Actions, `eva` (and all my other repositories) will be migrating to git.peppe.rs however, this might not be possible then.

**Comment by pickfire** [comment]
https://github.com/nerdypepper/eva/releases/tag/v0.3.0-alpha.1

I added support for linux and windows (not tested), not quite sure what I need to do about mac since it needs some appimage thing and that one needs some scripts, would be nice if someone can contribute it.

I guess can just close this for now. But if anyone is interested, can contribute the macos version.
