### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [NerdyPepper/eva#49]
Dear Akshay,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by pickfire** [comment]
Hi, sorry for the late reply.

Does something like https://github.com/nerdypepper/eva/pull/50/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f work for you? It will be bundled together during release but, I am not sure if it works (or how to get eva working) since I don't have windows and is not familiar with it.

**Comment by pickfire** [comment]
I guess https://github.com/nerdypepper/eva/releases/tag/v0.3.0-alpha.1 should work now? If it did not work, then can reopen this issue.

**Comment by sergeevabc** [comment]
@pickfire, thank you for letting me get to know this Eva app.
Lack of _exit_/_quit_ command and .0000000000 by default are deal breakers, alas.

**Comment by pickfire** [comment]
@sergeevabc Please open a new issue for it.

**Comment by sergeevabc** [comment]
Also, it doesn't accept the percentage: 
``` console
$ eva.exe 90-10%
Parser Error: Too many operators, too few operands
```
