### ISSUE TITLE
Moar Constants!

### ISSUE THREAD

**Issue by slbsh** [NerdyPepper/eva#73]
tried using g in a calculation and it failed misurably lol, here's two new constants I think would be useful:

```
c = 299,792,458 (speed of light)
g = 9.806,65 (standard gravity)
```

**Comment by StHagel** [comment]
While I think mathematical constants are always useful to have, physical constants have their fair share of problems.
`g` for example is not a universal constant and the value of ~9.80665 is only an approximation used in most textbooks.
The speed of light `c` does not have this problem, since its value is fixed to 299792458, it is only so in SI units. Different unit systems, such as CGS, natural units, or even imperial have different values for different constants, even universal and fixed ones. What you are looking for would be a computational system, which supports units.
